### PR TITLE
Docker compatibility using a Dockerfile

### PR DESCRIPTION
**Pull request by random-robbie**
Working docker container.

```
docker build -t acstis .
docker run -it acstis:latest

```

### CODE REVIEW

**Comment by tijme** [comment]
Hi @random-robbie,

Really awesome to get a pull request from you 😄, thank you for contributing !

I'm not using Docker myself but I checked out the documentation and found a deprecation notice that applies to this pull request.

**Maintainer Label**
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

I think this should now be `LABEL maintainer="txt3rob@gmail.com"`

Please correct me if I'm wrong.

**Review by random-robbie — COMMENTED** [review]
updated the label

**Comment by random-robbie** [comment]
Hey dude,

Updated it now.

works wonders in docker.

**Comment by tijme** [comment]
Thanks again for your contribution. I just merged the Docker file to the master branch 😄 .

**Comment by random-robbie** [comment]
👍 brilliant hopefully it helps others get it up and running.

**Pull request merged**
